project:
  type: website

website:
  title: mag4
  favicon: images/favicon.png
  navbar:
    background: primary
    search: true
    left:
      - text: "Microprobe"
        file: microprobe/epma-intro.qmd
      - text: "SEM"
        file: sem/sem-intro.qmd
      - text: "µ.XRF"
        file: mu_xrf/mu_xrf-intro.qmd
      - text: "Periphery"
        file: periphery/periphery-intro.qmd
      # - text: "Mass Spectrometry"
      #   file: mass-spec/mass-spec-intro.qmd
      - text: "Resources"
        file: resources/resources-intro.qmd
      - text: "Courses"
        menu:
          - text: 'Data Science'
            href: courses/data_science.qmd
          - text: 'Data Science Short Course'
            href: https://hezel2000.quarto.pub/dmg-data-science-short-course # https://datascienceshortcourse.streamlit.app
          - text: 'Kosmochemie'
            href: courses/cosmochemistry.qmd
          - text: 'Mikroanalytik'
            href: https://hezel2000.quarto.pub/mikroanalytik/
          - text: 'Geochemie I - Kosmochemie-Teil'
            href: https://hezel2000.quarto.pub/geochemie-1/
          - text: 'Umweltwissenschaften - Mikroanalytik-Teil'
            href: https://hezel2000.quarto.pub/umweltwissenschaften-mikroanalytik/
      - text: "All Apps"
        file: allapps/allapps.qmd
  
  sidebar:    
    - title: "Welcome"
      collapse-level: 1
      contents:
        - microprobe/epma-intro.qmd
        - section: 'Measurements'
          contents:
          - microprobe/data-access/request-time.qmd
          - microprobe/data-access/access-data.qmd
          - microprobe/data-access/kadi4mat-backend-eln.qmd
        - section: 'Flank Method'
          contents:
          - microprobe/flank-method/welcome.qmd
          - microprobe/flank-method/basics.qmd
          - microprobe/flank-method/data-reduction-program.qmd
          - microprobe/flank-method/video-tutorials.qmd
          - microprobe/flank-method/publications.qmd
          - microprobe/flank-method/code.qmd
          - microprobe/flank-method/glossary.qmd
        - microprobe/epma-tutorials/epma-tutorials.qmd
        - microprobe/trouble-shooting/trouble-shooting.qmd
        - microprobe/tools/resources.qmd
    
    - title: 'SEM'
      collapse-level: 1
      contents:
        - sem/sem-intro.qmd
        - section: 'Tutorials'
          contents:
            - sem/sem-tutorials/sem-tutorial.qmd
            - sem/sem-tutorials/ebsd-tutorial.qmd

    - title: "µ.XRF"
      collapse-level: 1
      contents:
        - mu_xrf/mu_xrf-intro.qmd
        - section: 'Tutorials'
          contents:
            - mu_xrf/mu_xrf-tutorials/mu_xrf-tutorial.qmd

    - title: "Periphery"
      collapse-level: 1
      contents:
        - periphery/periphery-intro.qmd
        - section: 'Tutorials'
          contents:
            - periphery/periphery-tutorials/preparation-tutorial.qmd

    # - title: "Mass-Spectrometry"
    #   collapse-level: 1
    #   contents:
    #     - section: 'Introduction'
    #       contents:
    #         - mass-spec/mass-spec-intro.qmd
    #     - section: 'B-isotopes'
    #       contents:
    #     #    - mass-spec/boron/documentation.qmd
    #         - mass-spec/boron/application.qmd
     #   - section: 'Fe-isotopes'
     #     contents:
     #       - mass-spec/iron/basics.qmd
     #       - mass-spec/iron/data reduction.qmd
    
    
    - title: "Resources"
      collapse-level: 1
      contents:
        - resources/resources-intro.qmd
        - resources/visualising-geochemical-databases.qmd
        - resources/powder-standards.qmd
        - resources/otherwebresources.qmd
        - resources/glossary.qmd

  cookie-consent:
    type: express
    style: simple
    palette: light
    policy-url: https://hezel2000.github.io/mag4/about.html
  

format:
  html:
    theme: cosmo
    toc: true

    # cookie banner
    include-in-header:
      - text: |
          <link rel="stylesheet"
                href="gdpr/cookieconsent-3.0.1/cookieconsent.css"
                media="print" onload="this.media='all'">
    include-after-body:
      - text: |
          <script defer src="gdpr/cookieconsent-3.0.1/cookieconsent.umd.js"></script>
          <script defer src="gdpr/cookieconsent-3.0.1/cookieconsent-init.js"></script>