# Request Time

## EPMA measurement request & info
Please fill out the form below.

<form id="epma_measurement_info" action="https://formspree.io/f/xkgnnvnz" method="POST">

  <label for="Name">Name</label>
  <input type="name" name="name" id="email-address" placeholder="First, Last" required=""><br>
  <label for="email-address">Email Address</label>
  <input type="email" name="_replyto" id="email-address" placeholder="email@em.uni-frankfurt.de" required="">
  
  <label for="rss">rectangular standard sample(s)</label>
  <input type="number" name="rectangular_standard_sample(s)" id="rss" placeholder="0" required=""><br>
  <label for="1irm">1" round mount(s)</label>
  <input type="number" name="1_inch_round_mount(s)" id="1irm" placeholder="0" required=""><br>
  <label for="1irs">1" round section(s)</label>
  <input type="number" name="1_inch_round_section(s)" id="1irs" placeholder="0" required=""><br>
  <label for="other">other</label>
  <input type="number" name="other" id="other" placeholder="0" required="">

  <label>I want to do</label><br>
  <label for="point_analyses">
      <input type="checkbox" id="point_analyses" name="point_analyses" value="point_analyses">
      point analyses
  </label><br>
  <label for="line_analyses">
      <input type="checkbox" id="line_analyses" name="line_analyses" value="line_analyses">
      line analyses
  </label><br>
  <label for="element_maps">
      <input type="checkbox" id="element_maps" name="element_maps" value="element_maps">
      element maps
  </label><br>
  <label for="cl_images">
      <input type="checkbox" id="cl_images" name="cl_images" value="cl_images">
      CL images
  </label><br>

  <label for="sample_names">Sample names</label><br>
  <textarea id="sample_names" name="sample_names" rows="4" cols="50" placeholder="List of sample names separated by commas." required=""></textarea><br>
  <label for="elements">Elements to be measured</label><br>
  <textarea id="elements" name="elements" rows="4" cols="50" placeholder="List of elements separated by commas." required=""></textarea><br>
  <label for="description">Description</label><br>
  <textarea id="description" name="description" rows="4" cols="50" placeholder="This descripiton will be included in the ELN (electronic lab notebook) record."  required=""></textarea><br>
  <label for="preferred_date">Preferred Date(s)</label><br>
  <textarea id="preferred_date" name="preferred_date" rows="4" cols="50" placeholder="Should I get data protection right for the calender below, this could be used as a guideline."></textarea><br>
  <label for="comment">Comment</label><br>
  <textarea id="comment" name="comment" rows="4" cols="50" placeholder="Anything else I should know for your measurement session? Measurement parameter preferences? Dietary needs?"></textarea><br>

  <label>Are the samples coated?</label><br>
  <label for="all_coated">
  <label for="yes" style="display: inline-block; margin-right: 20px;">
    <input type="radio" id="all_coated" name="all_coated" value="all_coated" required>
    All samples are coated
  </label>
  <label for="no" style="display: inline-block; margin-right: 20px;">
    <input type="radio" id="all_coated" name="all_coated" value="all_coated" required>
    All or some samples need coating
  </label><br>

  <label>Is it clear what you want to measure, or does this need to be discussed beforehand?</label><br>
  <label for="clear_what_to_do">
  <label for="yes" style="display: inline-block; margin-right: 20px;">
    <input type="radio" id="clear_what_to_do" name="clear_what_to_do" value="clear_what_to_do" required>
    It is clear
  </label>
  <label for="no" style="display: inline-block; margin-right: 20px;">
    <input type="radio" id="clear_what_to_do" name="clear_what_to_do" value="clear_what_to_do" required>
    It is not clear, needs to be discussed
  </label><br>


  <label for="gdpr">
    <input type="checkbox" id="gdpr" name="gdpr" value="gdpr" required="">
    I accept the <a href="https://gdpr-info.eu" target="_blank">GDPR terms and conditions</a>.
  </label><br>

  <!-- <input type="submit" value="Submit"> -->
  <form action="/your-action-url" method="post">
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</form>

<p id="thankYouMessage" style="display:none;">Danke für Deinen Beitrag.</p>

## Plan your sessions
Bring your documentation where and what you want to measure  
Room temperature is at a constant 20ºC  
Power sockets are available  
There is neither WiFi nor Eduroam  

## Calendar
Currently not active.
<iframe src="https://calendar.google.com/calendar/embed?height=600&wkst=2&ctz=Africa%2FCeuta&showPrint=0&showTz=0&src=ZTkxYjFhYjUxY2U4MmFmOGNjNDkwMWFhOWQ5MTk5NTc4YzIwY2E3YzM4YTJhNDM1NDM0ZGEzMmNmYzg0NzZlNEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t&color=%234285F4&color=%23E67C73" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

  <!--
  Dropdown menu
  <label for="1irs">
  <select name="state" required="">
    <option value="" selected="" disabled="">sample type</option>
    <option value="rss">rectangular standard sample</option>
    <option value="1irm">1" round mount</option>
    <option value="1irs">1" round section</option>
    <option value="other">other</option>
  </select> -->