---
title: 'Microanalytic'
---

# Kurs-Link & Überblick
<a href="https://geocourses.streamlit.app/Microanalysis">Hier</a> geht es zum Kurs Mikroanalytik.

**Die Veranstaltung besteht aus**
ca. 100 Seiten Skript, aufgeteilt in die 3 Teilskripte
ca. 70 Videos  mit >10 Stunden Material
>300 Selbstlern-Fragen mit Antworten
>20 Aufgaben zur gemeinsamen Lösung in den Präsenzphasen
ca. 10 zusätzlicher Dateien für verschiedene Aufgaben

# Ablaufplan SoSe 2023
**zu schauen bis ...**\
18.04. – 1 Labor-Tour: 1.1. – 1.5. [33:00]\
25.04. – 2 Atomaufbau & Elektronen-Konfigurationen: 2.1. – 2.5. [1:11:16] **(online)**\
02.05. – 3 Interaktion von Elektronen mit Material: 2.6. – 3.1. [36:22]\
09.05. – 4 Charakteristische Röntgenstrahlung als analytisches Werkzeug: 3.2. – 4.2.3. [58:55]\
16.05. – 5 Charakteristische Röntgenstrahlung als analytisches Werkzeug: 4.2.4. – 4.2.6. [47:04]\
23.05. – 6 Charakteristische Röntgenstrahlung als analytisches Werkzeug: 4.2.7. – 4.3.5.[51:52]\
30.05. – 7 Charakteristische Röntgenstrahlung als analytisches Werkzeug: 4.3.6. – 4.5. [51:49]\
06.06. – 8 Daten-Auswertung & -Darstellung: 5.1. – 5.3. [51:55] **(online)**\
13.06. – 9 Daten-Auswertung & -Darstellung: 5.4.1. – 5.4.4. [59:08]\
20.06. – 10 REM & RFA: Kapitel 6 [27:26]\
27.06. – 11 Vorbereitung auf den praktischen Teil: Kapitel 7 [1:08:46]\
04.07. – 12 Probe-Klausur\

**Gesamtlaufzeit 13h 12min 33s**

# Kurs Überblick

## 1.  Labor-Tour: 1.1. – 1.5. [33:00]
In der ersten Veranstaltung lernen wir die verschiedenen Labore und Geräte kennen. Studiert dafür das gesamte erste Kapitel ›Labor-Tour‹.

## 2.  Atomaufbau & Elektronen-Konfigurationen: 2.1. – 2.5. [1:11:16]
Diese fast noch erste Einheit wird Dir etwas abverlangen – allerdings: je besser wir die atomphysikalischen Grundlagen verstehen, sowie die dazu gehörigen Beschreibungen und das dafür verwendete Vokabular beherrschen, umso leichter wird es uns anschließend fallen, das zentrale Prinzip der Element-Bestimmung mit EDS und WDS an Mikrosonde, Raster, RFA – sowie verwandter Geräte wie das Transmissionselektronen-Mikroskop (TEM) zu verstehen. Nicht alle Details müssen über die Zeit hängen bleiben. Wenn man aber einmal verstanden hat, wie es funktioniert, lässt man sich später nicht mehr so leicht verwirren. Und das ist viel wert.
Also, dran bleiben wenn es heißt sich durch diese etwas längere Einheit mit den Kapiteln 2.1. bis 2.5. durchzuarbeiten. Die nächsten werden dafür wieder kürzer. Versprochen.

## 3.  Interaktion von Elektronen mit Material: 2.6. – 3.1. [36:22]
Das vorige Thema setzt sich noch etwas fort, denn bei der Interaktion der Elektronen mit Materie gibt es noch allerlei weitere Effekte, die wir kennen müssen. Viele dieser Themen sind wichtig, um später die quantitative Analyse zu verstehen. Das Wissen gegen Ende von Kapitel 2 benötigen wir Grundlage für bildgebende Verfahren, die der Inhalt von Kapitel 3 sind, und mit denen wir hier schon ein wenig beginnen.

## 4. Charakteristische Röntgenstrahlung als analytisches Werkzeug: 3.2. – 4.2.3. [58:55]
Wir lernen die beiden verbleibenden, wichtigen bildgebenden Verfahren kennen: SE- und CL-Bilder. Anschließend geht es mit einem neuen Thema los: der Charakteristischen Röntgenstrahlung als analytisches Werkzeug. Mit dem zuvor gewonnen Rüstzeug lernen wir nun, wie wir die Zusammensetzung von Proben bestimmen können. In einem zunächst kurzen Kapitel wird das Energie-Dispersive Spektrometer (EDS) vorgestellt. Anschließend lernen wir die wichtigste und zentrale Grundlage der Winkel-Dispersiven Spektrometerie: die Selektion der Röntgenstrahlung eines Elements mit Hilfe der Bragg-Bedingung, sowie der Rowland-Kreis Geometrie.

## 5. Charakteristische Röntgenstrahlung als analytisches Werkzeug: 4.2.4. – 4.2.6. [47:04]
Diese Einheit beschäftigt sich mit dem Röntgendetektor. Diese Gaszähler erlauben es Röntgenstrahlung höherer Ordnung auszuschließen, was sehr praktisch ist, um damit Interferenzen zu unterdrücken. Das Thema ist nicht ganz unkomplex, daher ist die Gesamtzeit der Videos zwar etwas kürzer, jedoch müssen besonders die beiden Kapitel/Videos 4.2.4 & 4.2.6 sehr gut studiert werden, um das Thema wirklich zu verstehen. Es wäre nicht erstaunlich, wenn es diesmal im Besondern nötig wäre, zwischendurch anzuhalten, und sich die Dinge durch z.B. eigene Skizzen selbst noch einmal klar zu machen.

## 6. Charakteristische Röntgenstrahlung als analytisches Werkzeug: 4.2.7. – 4.3.5.[51:52]
Ein zentrales Element um Proben zu messen, ist die Standardisierung, welche wir in dieser Einheit kennen lernen. Wir lernen außerdem erste, konkrete Parameter und Bedingungen kennen, mit denen eine Probe gemessen werden kann, und einige Dinge wie Matrix-Korrektur, Nachweisgrenze, etc. die für eine erfolgreiche Messung beachtet werden müssen. 

## 7. Charakteristische Röntgenstrahlung als analytisches Werkzeug: 4.3.6. – 4.5. [51:49]
Im letzten Teil von Kapitel 4 schauen wir uns noch Interferenzen und den Chemical Peak Shift, welche die Messung beeinflussen können. Dann wollen wir jedoch wissen, was und wie wir mit der Mikrosonde oder dem Rasterelektronen-Mikroskop messen können. Schließlich gibt es ein wichtiges Video dazu, was man überlegen sollte oder muss, bevor man am Messtag im Labor steht. Wichtig ist das Video, da es Dir hilft eine erfolgreiche Mess-Kampagne durchführen.

## 8.  Daten-Auswertung & -Darstellung: 5.1. – 5.3. [51:55]
Wir können nun erfolgreich an der Mikrosonde und eigentlich auch dem REM messen. Aber was tun mit all den Daten? Zunächst müssen wir wissen, wie wir sie vom Gerät auf unseren Computer transferieren. Als erstes wollen wir dann natürlich wissen, wie genau wir gemessen haben, bzw. mit welchem Vokabular wir diese Genauigkeit kommunizieren. Dann sind wir natürlich neugierig, wie denn nun die gemessenen Minerale und andere Phasen genau zusammen gesetzt sind. Das erfahren wir, indem wir deren Mineral- und Strukturformel berechnen. Um all das geht es in diesen Kapiteln.

## 9.  Daten-Auswertung & -Darstellung: 5.4.1. – 5.4.4. [59:08]
Ein wichtiger Teil der Analytik ist die Darstellung der Daten in aussagekräftigen und übersichtlichen Diagramme und Tabellen. Dazu schauen wir uns zunächst an, wie die Daten für typische Diagramme aufbereitet werden – nämlich als Element-Konzentrationen oder normiert. Dann arbeiten wir uns ein wenig durch typische Diagramm-Typen, um zu lernen und zu verstehen, was das eigentlich für Diagramme sind, die wir da häufig sehen, und regelmäßig selbst nutzen. Schließlich lernen wir ein wenig welche Elemente bei Diagrammen und Tabellen wichtig sind, und wie diese genutzt werden können und sollten.

## 10.  REM & RFA: Kapitel 6 [27:26]
In dieser vergleichsweise kurzen Einheit lernen wir den Unterschied zwischen EPMA und REM etwas genauer kennen, und weshalb das REM sehr viel mehr ein Mikroskop ist. An unserem REM haben wir außerdem einen EBSD-Detektor, der vorgestellt wird, und was man damit anstellen kann. Im zweiten Teil wird die RFA vorgestellt, worin sich diese von der EPMA unterscheidet, und welche unterschiedlichen Einsatzgebiete es für die RFA gibt, und damit, in welch unterschiedlichen Ausführungen RFAs gebaut werden.

## 11.  Vorbereitung auf den praktischen Teil: Kapitel 7 [1:08:46]
In Vorbereitung auf den praktischen Teil gibt es zunächst Video-Trockenübungen. Diese sind sehr hilfreich, um am Gerät nicht gleich verloren zu sein, sondern schon mit Vorkenntnis zu starten. Daher zum Bingen und immer wieder schauen ein paar Videos mit Einblicken von der Sonde wie diese bedient wird. Abgerundet durch ein paar kurze Impressionen rund um und aus der Sonde.

## 12.  Probe-Klausur
Die Probe-Klausur ist ähnlich der tatsächlichen Klausur. Der Umfang ist etwas kürzer, da Du im Anschluss noch die Klausur einer Kommilitonin eins Kommilitonen korrigieren wirst.


# Auf dem Weg zur Probeklausur

## Sinn und Zweck dieser Übung
Es gibt diese Probeklausur, damit Du eine Idee davon bekommst, was Dich bei der echten Klausur erwartet. Als Vorbereitung dafür gibt es keine weiteren Inhalte oder Videos – sondern wiederhole alles, das wir bislang durchgegangen sind und geübt haben.

## Ablauf
Die Klausur dauert ca. 50 min., also etwas länger oder kürzer als im Modul vorgegeben, je nachdem ob Du Dir den Kurs für BSc (30 min als möglicher Teil einer kumulativen Modulabschlussklausur; max. Punktzahl: 33) oder MSc (90 min als mögliche exemplarische Modulabschlussklausur; max. Punktzahl: 100) anrechnen lässt. Du schreibst die Klausur für Dich allein. Schummeln wird nicht kontrolliert, diese Probeklausur dient allein Deiner eigenen Einschätzung.
Anschließend kommst Du in eine 2er oder 3er Gruppe, erhältst die Lösung für die Klausur, und Ihr korrigiert gegenseitig Eure Klausuren. Das sollte ca. 15 min dauern.

## Halb-Finale
Zum Abschluss haben wir knapp 30 min. Zeit die Klausur gemeinsam durchzusprechen, allgemeine Fragen zu stellen und zu beantworten, oder letzte Unklarheiten auszuräumen.

## Fünf Beispiel-Fragen für die Vorbereitung (Gesamtpunktzahl: 33)
Notwendige Unterlagen wie z.B. Tabellen zum Nachschlagen werden zur Verfügung gestellt.

**Frage 1** *(5 Punkte)*\
Nenne 2 Elementpaare (also 2 x 2 Elemente) deren charakteristische Röntgenstrahlung möglicherweise eine Linienüberlagerung zeigen könnten.

**Frage 2** *(5 Punkte)*\
Worin können sich Proben ähneln und/oder unterscheiden die mit der EPMA oder mit dem REM untersucht werden.

**Frage 3** *(8 Punkte / 3 Punkte)*\
Erkläre schematisch die Funktionsweise des Gaszählers. Wozu wird dieser verwendet?

**Frage 4** *(4 Punkte)*\
Wie hoch sollte die Beschleunigungsspannung sein um Hf,Lα anzuregen? Und wie hoch der Strom?

**Frage 5** *(8 Punkte)*\
Elemente mit charakteristischer Linien höherer Ordnung können die charakteristischen Linien anderer Elementen überlagern. (i) An welcher Stelle in der EPMA, und (ii) wie können diese Linien höherer Ordnung von der Zählung ausgeschlossen werden.


# Kommentiertes Literaturverzeichnis

**EPMA, REM und XRF**

**Llovet+ 2020. Electron probe microanalysis: a review of recent developments and applications in materials science and engineering.**\
Prog Mater Sci 116 p, 100673 https://doi.org/10.1016/j.pmatsci.2020.100673 \
Ein sehr übersichtlicher Review-Artikel, der alle wichtigen Aspekte zur Mikrosonde auf ca. 90 Seiten zusammen fasst.

**Hawkes+Spence (Eds.) 2019. Handbook of Microscopy.**\
1543 p, Springer, Springer Nature Switzerland. https://doi.org/10.1007/978-3-030-00069-1 \
Ein gewaltiges Kompendium, das auf 1500 Seiten in vielen Einzelartikeln umfassend alle Aspekte der Elektronen-Mikroskopie abarbeitet. Die Mikrosonde fehlt, da sie offensichtlich mehr in die chemische Analytik und nicht die Mikroskopie fällt.

**Goldstein+ 2018. Scanning Electron Microscopy and X-Ray Microanalysis.**\
Second Edition, Plenum Press, New York https://link.springer.com/book/10.1007/978-1-4939-6676-9 \
Das Standardwerk beschreibt alles wichtige zur Mikrosonde in Einzelartikeln auf gut 500 Seiten.

**Rinaldi+Llovet 2015. Electron Probe Microanalysis: A Review of the Past, Present, and Future.**\
Microsc Microanal 21, 1053–1069 https://doi.org/10.1017/S1431927615000409 \
Ein interessanter Review-Artikel, der auch auf geschichtliche Aspekte der Mikrosonde eingeht.

**Reed, S. J. B. 2005. Electron Microprobe Analysis and Scanning Electron Microscopy in Geology.**\
Cambridge University Press. https://www.cambridge.org/core/books/electron-microprobe-analysis-and-scanning-electron-microscopy-in-geology/A7BD5CF9A6E6D9E2360E4F378C81D002 \
Das kompakte Buch fasst alles Wichtige zur Mikrosonde und dem REM auf gut 180 Seiten zusammen.